-- 회원 테이블
CREATE TABLE MEMBER (
    MEMBER_ID       NUMBER          PRIMARY KEY,
    NAME            VARCHAR2(100)   NOT NULL,
    PHONE           VARCHAR2(20)    NOT NULL,
    EMAIL           VARCHAR2(50)    NOT NULL UNIQUE,
    GENDER          CHAR(1)         NOT NULL, -- 'M' 또는 'F'
    BIRTHDATE       DATE,
    MEMBER_REGDATE  DATE DEFAULT SYSDATE NOT NULL
);

CREATE SEQUENCE SEQ_MEMBER_ID
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- 멤버십 테이블
CREATE TABLE MEMBERSHIP (
    MEMBERSHIP_ID NUMBER PRIMARY KEY,
    MEMBER_ID NUMBER NOT NULL,
    MEMBERSHIP_TYPE VARCHAR2(50),
    PERIOD_MONTH NUMBER,
    START_DATE DATE,
    END_DATE DATE,
    PRICE NUMBER,
    STATUS VARCHAR2(20),
    CONSTRAINT FK_MEMBER_ID FOREIGN KEY (MEMBER_ID)
        REFERENCES MEMBER(MEMBER_ID)
);